### ISSUE TITLE
Client Credentials

### ISSUE THREAD

**Issue by levine1726** [nickrodgers42/running#1]
Have you thought about using a client credential workflow?

**Comment by nickrodgers42** [comment]
"hAVe YOU ThougHT abOUt USINg a cLiEnt CrEdenTIaL WorkflOW?"
![image](https://github.com/nickrodgers42/running/assets/19293901/f8228147-c408-4062-848a-07877a8aba04)

**Comment by levine1726** [comment]
wow this is hurtful I'm crying and shaking

**Comment by levine1726** [comment]
please re-open you haven't addressed the issue

**Comment by levine1726** [comment]
Have you thought about reconsidering this request?
